# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_formats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logformats',
            name='log_format',
            field=models.TextField(max_length=100),
        ),
    ]
