# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_formats', '0003_auto_20161110_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='logformats',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
