# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ip', models.CharField(max_length=20, null=True)),
                ('format_id', models.IntegerField()),
                ('site_id', models.IntegerField(null=True)),
                ('status', models.IntegerField()),
                ('response_bytes_clf', models.CharField(max_length=30, null=True)),
                ('remote_host', models.CharField(max_length=50, null=True)),
                ('request_method', models.CharField(max_length=4, null=True)),
                ('request_url_path', models.CharField(max_length=500, null=True)),
                ('time_received_tz_isoformat', models.CharField(max_length=50, null=True)),
                ('time_us', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='apachelog',
            unique_together=set([('site_id', 'local_ip', 'status', 'time_received_tz_isoformat', 'request_url_path', 'response_bytes_clf', 'request_method')]),
        ),
    ]
