# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apache_logs', '0002_auto_20161115_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='apachelog',
            name='time_received_tz',
            field=models.DateTimeField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='time_received_tz_isoformat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
