# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('site_name', 'site_url')]),
        ),
    ]
